name: Manual Dependabot Trigger

on:
  workflow_dispatch:

jobs:
  trigger-dependabot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Create a new unique branch and checkout
        run: |
          UNIQUE_BRANCH_NAME="trigger-dependabot-$(date +%s)"
          git checkout -b $UNIQUE_BRANCH_NAME
          echo "UNIQUE_BRANCH=$UNIQUE_BRANCH_NAME" >> $GITHUB_ENV

      - name: Update timestamp in dependabot.yml
        run: |
          TIMESTAMP=$(date -u)
          TIMESTAMP_LINE="# Triggered update: $TIMESTAMP"
          DEPENDABOT_FILE=".github/dependabot.yml"
          # Check if the timestamp line exists and replace it, or append it if it doesn't
          if grep -q "^# Triggered update:" "$DEPENDABOT_FILE"; then
            sed -i "s|^# Triggered update:.*|$TIMESTAMP_LINE|" "$DEPENDABOT_FILE"
          else
            echo -e "\n$TIMESTAMP_LINE" >> "$DEPENDABOT_FILE"
          fi

      - name: Commit changes
        run: |
          git config user.name 'rjar2020'
          git config user.email 'rjar2020@gmail.com'
          git add .github/dependabot.yml
          git commit -m "Trigger Dependabot on demand [skip ci]" || echo "No changes to commit"

      - name: Push to new unique branch
        run: |
          git push origin ${{ env.UNIQUE_BRANCH }}

      - name: Create Pull Request using GitHub CLI
        run: |
          gh pr create --title "Trigger Dependabot on demand" --body "This is an automated pull request to update the dependency files." --base main --head ${{ env.UNIQUE_BRANCH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
