name: Manual Dependabot Trigger

on:
  workflow_dispatch:

jobs:
  trigger-dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Create a new unique branch
        run: |
          UNIQUE_BRANCH="trigger-dependabot-$(date +%s)"  # Create a unique branch name using a timestamp
          git checkout -b "$UNIQUE_BRANCH"

      - name: Add timestamp to dependabot.yml
        run: |
          TIMESTAMP=$(date -u)
          echo "Adding timestamp to the dependabot.yml"
          sed -i "1s/^/# Triggered update: $TIMESTAMP\n/" .github/dependabot.yml

      - name: Commit changes
        run: |
          git config user.name 'rjar2020'
          git config user.email 'rjar2020@gmail.com'
          git add .github/dependabot.yml
          git commit -m "Trigger Dependabot on demand [skip ci]" || exit 0

      - name: Push to new unique branch
        run: |
          git push origin "$UNIQUE_BRANCH"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ steps.create-branch.outputs.branch }}
          base: main
          title: 'Trigger Dependabot on demand'
          body: 'This is an automated pull request to update the dependency files.'
