name: Manual Dependabot Trigger

on:
  workflow_dispatch:

jobs:
  trigger-dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Create a new unique branch and checkout
        run: |
          UNIQUE_BRANCH_NAME="trigger-dependabot-$(date +%s)"
          git checkout -b $UNIQUE_BRANCH_NAME
          echo "UNIQUE_BRANCH=$UNIQUE_BRANCH_NAME" >> $GITHUB_ENV

      - name: Verify branch creation
        run: git branch

      - name: Add timestamp to dependabot.yml
        run: |
          TIMESTAMP=$(date -u)
          echo "Adding timestamp to the dependabot.yml"
          echo -e "# Triggered update: $TIMESTAMP\n$(cat .github/dependabot.yml)" > .github/dependabot.yml

      - name: Commit changes
        run: |
          git config user.name 'rjar2020'
          git config user.email 'rjar2020@gmail.com'
          git add .github/dependabot.yml
          git commit -m "Trigger Dependabot on demand [skip ci]" || exit 0

      - name: Push to new unique branch
        run: |
          git push origin $UNIQUE_BRANCH

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.UNIQUE_BRANCH }}
          base: main
          title: 'Trigger Dependabot on demand'
          body: 'This is an automated pull request to update the dependency files.'
